float:
  any:
  - name: deg
    module: vibe.algorithms.deg
    constructor: DEG
    singularity_image: deg
    disabled: false
    gpu: false
    ood: false
    base_args: ['@metric']
    run_groups:
      base:
        args:
          k: [48]
          opt_target: ['LowLID']
          prune_non_rng: [false]
        query_args:
          eps_or_ef: [0.0, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.1, 0.12, 0.15, 0.2, 0.25, 0.3]
  - name: deg-qg
    module: vibe.algorithms.deg
    constructor: QG
    singularity_image: deg
    disabled: false
    gpu: false
    ood: false
    base_args: ['@metric']
    run_groups:
      linear_pool:
        args:
          k: [48]
          opt_target: ['LowLID']
          prune_non_rng: [false]
        query_args:
          rerank_size_factor: [1.0, 1.15, 1.35]
          eps_or_ef: [0.0, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.1, 0.12, 0.15, 0.2, 0.25, 0.3]
