float:
  any:
  - name: deg
    module: vibe.algorithms.deg
    constructor: DegANN
    singularity_image: deg
    disabled: false
    gpu: false
    ood: false
    base_args: ['@metric']
    run_groups:
      base:
        args:
          k: [16, 24, 30, 40, 48]
          opt_target: ['LowLID', 'StreamingData']
          prune_non_rng: [false, true]
          threads: [1]
          query_dtype: ['float32']
        query_args:
          search_eps: [0.0, 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.1, 0.12, 0.15, 0.2, 0.25, 0.3]
          rerank_size_factor: [1.0, 1.2, 1.5, 2.0]
