name: BuildAndTest

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev

defaults:
  run:
    working-directory: python

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, macos-13, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    if: "contains(github.event.head_commit.message, '+ci')"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Add requirements
      run: python -m pip install --upgrade setuptools pybind11>=2.12.0 cibuildwheel

    - name: Copy Build Files
      run: python setup.py copy_build_files

    - name: Build Packages
      run: cibuildwheel --output-dir "dist"
      env:
        CIBW_ARCHS: auto64
        CIBW_BUILD_FRONTEND: "pip; args: --verbose"
        CIBW_ENVIRONMENT: "FORCE_AVX2=1"
        CIBW_ENVIRONMENT_MACOS: "FORCE_AVX2=1 MACOSX_DEPLOYMENT_TARGET=10.15"
        CIBW_SKIP: "cp313-*"

  build_sdist:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '+ci')"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Add requirements
      run: python -m pip install --upgrade setuptools pybind11>=2.12.0

    - name: Copy Build Files
      run: python setup.py copy_build_files

    - name: Build Source Distribution
      run: python setup.py sdist
